#!/usr/bin/env ruby

require "timeout"

ARGV.each do |k|
    begin
        Process.kill("TERM", k.to_i)
        Timeout::timeout(30) do
            begin
              sleep 1
            end while !!(`ps -p #{k}`.match /#{k}/)
        end
    rescue Timeout::Error
        Process.kill("KILL", k.to_i)
    end
    
end
