#!/usr/local/bin/ruby

# this file should be called from /etc/init.d
=begin
sudo su
service rabbitmq-server start
rabbitmq-plugins enable rabbitmq_management
rabbitmqctl add_user <user> <password>
rabbitmqctl set_user_tags <user> <password>
rabbitmqctl set_permissions -p / oddidev ".*" ".*" ".*"
rabbitmqctl delete_user guest
sudo rabbitmqctl list_users
=end

require File.expand_path('../config/environment',  __FILE__)
require File.expand_path('../config/boot',  __FILE__)
require "bunny"

require  "#{Dir.pwd}/app/models/rabbit_receiver.rb"
RabbitReceiver.consumers
