# is overriden by OpsWorks
development: &default
  adapter: mysql2
  encoding: utf8
  database: dash_development
  username: root
  password:
  port: 3306
  socket: /tmp/mysql.sock

staging:
  <<: *default

production:
  
