development: &defaults
  :address: smtp.gmail.com
  :port: 587
  :domain: gmail.com
  :authentication: plain
  :user_name: oddidev@gmail.com
  :password: "oddi3600ROCKS$#1"
  :enable_starttls_auto: true
  :receivers: "epugh@bbg.gov"
staging:
  <<: *defaults
  
production:
  :address: email-smtp.us-east-1.amazonaws.com
  :port: 587
  :domain: amazonaws.com
  :authentication: :login
  :user_name: AKIAJH2KYA7N5VUKS5JQ
  :password: AlHU97IYinKaMgjEDhGH6UjeL/vGD69d/f9xiDHHmEOU'
  :enable_starttls_auto: true
  :receivers: "oddidev@bbg.gov"
  
# this works in development per this thead
# http://stackoverflow.com/questions/4313177/sending-mail-with-rails-3-in-development-environment
