# is overriden by OpsWorks
development: &defaults
  :address: smtp.gmail.com
  :port: 587
  :domain: gmail.com
  :authentication: plain
  :user_name: oddidev@gmail.com
  :password: "oddi3600BBG2015"
  :enable_starttls_auto: true
  :receivers: "liwliu@bbg.gov"
staging:
  <<: *defaults
  
production:
  :address: email-smtp.us-east-1.amazonaws.com
  :port: 587
  :domain: amazonaws.com
  :authentication: :login
  :user_name: 
  :password: 
  :enable_starttls_auto: true
  :receivers: 
