development: &defaults
  host: 127.0.0.1
  username: oddidev
  password: ab530a13e45914982b

staging:
  <<: *defaults
  
production:
  host: 54.227.248.152
  username: oddidev
  password: ab530a13e45914982b
