access_key_id: AKIAJ6SMUFUSEH6MNZRA
secret_access_key: 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

development: &defaults
  bucket: uber-dashboard-socialscraper
  storage: s3
  path: ':contest/:attachment/:id/:style/:basename.:extension'

staging:
  <<: *defaults
  
production:
  bucket: uber-dashboard-socialscraper
  storage: s3
  path: s3://twitter/user/VOA_News/12JUN14_timeline.json)

# create s3 bucket
# https://console.aws.amazon.com/s3/home?region=us-east-1
