#https://sitecatalyst.omniture.com

development: &defaults
  company: "bbg"
  username: "API:BBG"
  shared_secret: "49703aab165281af7ff6616e4f7c53a2"
  rsid: "bbgprod"

staging:
  <<: *defaults
  
production:
  company: "bbg"
  username: "oddidev:BBG"
  shared_secret: "6c257ec67510138a37b8149d3b72d3d4"
  rsid: "bbgprod"
