#!/bin/sh
#
# rabbitmq-receiver RabbitMQ Ruby receiver
#
# chkconfig: - 80 05
# description: Run AMQP  receiver
#

### BEGIN INIT INFO
# Provides:          rabbitmq-receiver
# Required-Start:    $remote_fs $network
# Required-Stop:     $remote_fs $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Description:       RabbitMQ receievr
# Short-Description: Enable AMQP rabbitmq-receiver
### END INIT INFO

# this script works as init.d
ROOT_PATH=/home/oddev/cxp/current
PATH=/sbin:/usr/sbin:/bin:/usr/bin
NAME=rabbitmq-receiver
DAEMON=$ROOT_PATH/${NAME}
DESC="daemon "
USER=oddev
INIT_LOG_DIR=$ROOT_PATH/tmp
PID_FILE=$ROOT_PATH/tmp/receiver.id


test -x $DAEMON || exit 0

RETVAL=0
set -e

[ -f /etc/default/${NAME} ] && . /etc/default/${NAME}

. /lib/lsb/init-functions
. /lib/init/vars.sh

ensure_pid_dir () {
    PID_DIR=`dirname ${PID_FILE}`
    if [ ! -d ${PID_DIR} ] ; then
        mkdir -p ${PID_DIR}
        chown -R ${USER}:${USER} ${PID_DIR}
        chmod 755 ${PID_DIR}
    fi
}

remove_pid () {
    rm -f ${PID_FILE}
    log_daemon_msg "${PID_FILE} removed"
#    rmdir `dirname ${PID_FILE}` || :
}

start_receiver () {
  stop_receiver
  # touch ${PID_FILE}
  start-stop-daemon --start --chuid oddev --quiet --oknodo --pidfile $PID_FILE --exec $DAEMON > /tmp/mq-init.d.log 2>&1 &  
  log_daemon_msg "Started"
  true
}
stop_receiver () {
  # pid=`pidof RabbitReceiver.receive`
  pid=`pgrep -f RabbitReceiver`
  if [ "$pid" != "" ]; then
    kill -15 $pid
  fi
  pid=`pgrep -f script/run_receiver.rb`
  if [ "$pid" != "" ]; then
    kill -15 $pid
  fi
#  start-stop-daemon --retry TERM/5/KILL/5 --oknodo --stop --quiet --pidfile $PID_FILE 1>/dev/null
#   remove_pid
}
case "$1" in
    restart)
      log_daemon_msg "Restarting $DESC" "$NAME"
      if start_receiver
        then
            log_end_msg 0 || true
        else
            log_end_msg 1 || true
        fi
        ;;
    start)
      log_daemon_msg "Starting $DESC" "$NAME"
      if start_receiver
        then
            log_end_msg 0 || true
        else
            log_end_msg 1 || true
        fi
        ;;
    stop)
      log_daemon_msg "Stopping $DESC" "$NAME"
      if stop_receiver
      then
        log_end_msg 0
      else
        log_end_msg 1
      fi
    ;;
    *)
     echo "Usage: $0 {start|stop|restart}" >&2
        RETVAL=1
        ;;
esac

exit $RETVAL

